import type {
  ChatMessage,
  RecentSession,
  SessionMeta,
  TimelineNode,
} from './types';

export const sessionMeta: SessionMeta = {
  id: 'ses_8f3d',
  title: 'add dark mode to settings page',
  started: '14:22 Apr 19',
  model: 'claude-opus-4-7',
  status: 'active',
  tokens: 48213,
  cost: '$0.41',
  elapsed: '2m 48s',
  branch: 'feat/settings-dark-mode',
  cwd: '~/projects/aperture-web',
};

export const recentSessions: RecentSession[] = [
  {
    id: 'ses_8f3d',
    title: 'add dark mode to settings page',
    ago: 'now',
    status: 'active',
    model: 'opus-4.7',
  },
  {
    id: 'ses_7c01',
    title: 'refactor useBilling hook into service',
    ago: '41m',
    status: 'complete',
    model: 'opus-4.7',
  },
  {
    id: 'ses_6a92',
    title: 'audit telemetry pii redaction',
    ago: '2h',
    status: 'complete',
    model: 'sonnet-4.6',
  },
  {
    id: 'ses_5d18',
    title: 'debug websocket reconnect loop',
    ago: '5h',
    status: 'error',
    model: 'opus-4.7',
  },
  {
    id: 'ses_4b27',
    title: 'add batch export to admin panel',
    ago: 'yest',
    status: 'paused',
    model: 'sonnet-4.6',
  },
  {
    id: 'ses_3a14',
    title: 'migrate stripe to v18 api',
    ago: '2d',
    status: 'complete',
    model: 'opus-4.7',
  },
];

export const chatMessages: ChatMessage[] = [
  {
    id: 'm1',
    role: 'user',
    content:
      'add a dark mode toggle to the settings page. should persist across reloads and respect system preference by default.',
    timestamp: '14:22:04',
  },
  {
    id: 'm2',
    role: 'thinking',
    content:
      'Need to check existing theme infrastructure before adding state. If there\'s already a ThemeContext I should extend it, not duplicate. First: locate settings page and any theme-related files.',
    timestamp: '14:22:06',
  },
  {
    id: 'm3',
    role: 'assistant',
    content:
      'Looking into the project structure first - want to understand what theme infrastructure already exists so I extend rather than duplicate.',
    timestamp: '14:22:07',
    toolRefs: [
      { id: 'n3', label: 'settings files', tool: 'glob' },
      { id: 'n4', label: 'SettingsPage.tsx', tool: 'read' },
      { id: 'n5', label: 'ThemeContext.tsx', tool: 'read' },
    ],
  },
  {
    id: 'm4',
    role: 'assistant',
    content:
      'Found an existing ThemeContext - currently only stores `accent`. I\'ll extend it with `colorScheme` and wire the toggle through. Spawning a quick sweep for everywhere tokens get consumed so I don\'t miss a call site.',
    timestamp: '14:23:18',
    toolRefs: [{ id: 'n6', label: 'theme token sweep', tool: 'grep' }],
  },
  {
    id: 'm5',
    role: 'assistant',
    content:
      'Sweep came back: 14 files touch theme tokens but all resolve through the context - so extending the context covers all of them. Making the edits now.',
    timestamp: '14:24:02',
    toolRefs: [
      { id: 'n8', label: 'ThemeContext.tsx', tool: 'edit' },
      { id: 'n9', label: 'SettingsPage.tsx', tool: 'edit' },
    ],
  },
  {
    id: 'm6',
    role: 'thinking',
    content:
      'Tests are running. Before they finish - the hydration test is likely to flag this because colorScheme reads from localStorage on mount, which differs from SSR output. Need to be ready with a fix.',
    timestamp: '14:24:40',
  },
  {
    id: 'm7',
    role: 'assistant',
    content:
      '2 tests failed - hydration mismatch on initial render as expected. Two ways to fix this: (a) always render in "system" on SSR and sync on mount, or (b) read the cookie server-side. Going with (a) - no cookie plumbing needed and the flash is imperceptible.',
    timestamp: '14:25:11',
    toolRefs: [
      { id: 'n11', label: 'decision hydration strategy', tool: 'bash' },
      { id: 'n13', label: 'ThemeProvider.tsx', tool: 'edit' },
    ],
  },
  {
    id: 'm8',
    role: 'assistant',
    content:
      'Green. Dark mode toggle is live on /settings, persists to `theme.scheme` in localStorage, falls back to `prefers-color-scheme`. FOUC window is ~14ms on cold loads.',
    timestamp: '14:25:52',
    toolRefs: [{ id: 'n14', label: 'npm test passed', tool: 'bash' }],
  },
];

export const timelineNodes: TimelineNode[] = [
  {
    id: 'n1',
    kind: 'user',
    title: 'add a dark mode toggle to the settings page',
    subtitle: 'should persist across reloads respect system pref',
    timestamp: '00:00',
    status: 'complete',
    relatedChatId: 'm1',
  },
  {
    id: 'n2',
    kind: 'thinking',
    title: 'plan approach',
    preview:
      'Check for existing ThemeContext before adding state. Avoid duplicating infra.',
    thinking:
      'Need to check existing theme infrastructure before adding state. If there\'s already a ThemeContext I should extend it, not duplicate. First: locate settings page and any theme-related files.',
    timestamp: '00:02',
    duration: '0.4s',
    tokens: 612,
    status: 'complete',
    relatedChatId: 'm2',
  },
  {
    id: 'n3',
    kind: 'tool',
    toolKind: 'glob',
    title: 'glob',
    subtitle: '**/settings*.{ts,tsx}',
    preview: '2 matches src/pages/SettingsPage.tsx, src/pages/settings.test.tsx',
    timestamp: '00:03',
    duration: '38ms',
    status: 'complete',
    bashOutput:
      'src/pages/SettingsPage.tsx\nsrc/pages/settings.test.tsx',
  },
  {
    id: 'n4',
    kind: 'tool',
    toolKind: 'read',
    title: 'read',
    subtitle: 'src/pages/SettingsPage.tsx',
    preview: '218 lines uses useTheme() for accent only',
    timestamp: '00:05',
    duration: '12ms',
    status: 'complete',
  },
  {
    id: 'n5',
    kind: 'tool',
    toolKind: 'read',
    title: 'read',
    subtitle: 'src/theme/ThemeContext.tsx',
    preview: '64 lines exposes { accent, setAccent } - no colorScheme yet',
    timestamp: '00:07',
    duration: '9ms',
    status: 'complete',
  },
  {
    id: 'n6',
    kind: 'agent',
    title: 'explore - theme token usage',
    subtitle: 'sweep repo for direct token access',
    agentName: 'Explore',
    preview:
      '14 files touch theme tokens all go through useTheme() safe to extend centrally',
    timestamp: '00:14',
    duration: '42s',
    tokens: 8402,
    status: 'complete',
    agentChildren: ['n6a', 'n6b'],
  },
  {
    id: 'n6a',
    kind: 'tool',
    toolKind: 'grep',
    title: 'grep',
    subtitle: 'useTheme\\(\\)',
    preview: '14 matches across 14 files',
    timestamp: '00:16',
    duration: '71ms',
    status: 'complete',
  },
  {
    id: 'n6b',
    kind: 'tool',
    toolKind: 'grep',
    title: 'grep',
    subtitle: 'theme\\.(accent|scheme|color)',
    preview: '0 direct accesses all routed through hook',
    timestamp: '00:42',
    duration: '64ms',
    status: 'complete',
  },
  {
    id: 'n7',
    kind: 'thinking',
    title: 'extending context is safe',
    preview: 'No call sites bypass the hook - one change surface.',
    thinking:
      'Since every consumer goes through useTheme(), extending the context with colorScheme will propagate without touching individual components. That\'s one surface to change instead of 14.',
    timestamp: '01:01',
    duration: '0.3s',
    tokens: 318,
    status: 'complete',
  },
  {
    id: 'n8',
    kind: 'tool',
    toolKind: 'edit',
    title: 'edit',
    subtitle: 'src/theme/ThemeContext.tsx',
    preview: '+34 -4 added colorScheme + setColorScheme',
    timestamp: '01:08',
    duration: '0.8s',
    status: 'complete',
    diff: {
      file: 'src/theme/ThemeContext.tsx',
      additions: 34,
      deletions: 4,
      hunks: [
        {
          header: '@@ -1,18 +1,42 @@',
          lines: [
            { type: 'context', num: 1, text: "import { createContext, useContext, useState } from 'react';" },
            { type: 'remove', num: 2, text: "type Theme = { accent: string };" },
            { type: 'add', num: 2, text: "type ColorScheme = 'light' | 'dark' | 'system';" },
            { type: 'add', num: 3, text: "type Theme = {" },
            { type: 'add', num: 4, text: " accent: string;" },
            { type: 'add', num: 5, text: " colorScheme: ColorScheme;" },
            { type: 'add', num: 6, text: " setColorScheme: (s: ColorScheme) => void;" },
            { type: 'add', num: 7, text: "};" },
            { type: 'context', num: 8, text: "" },
            { type: 'context', num: 9, text: "const ThemeContext = createContext<Theme | null>(null);" },
          ],
        },
      ],
    },
  },
  {
    id: 'n9',
    kind: 'tool',
    toolKind: 'edit',
    title: 'edit',
    subtitle: 'src/pages/SettingsPage.tsx',
    preview: '+22 -0 toggle group w/ system / light / dark',
    timestamp: '01:32',
    duration: '0.6s',
    status: 'complete',
    diff: {
      file: 'src/pages/SettingsPage.tsx',
      additions: 22,
      deletions: 0,
      hunks: [
        {
          header: '@@ +48,22 @@',
          lines: [
            { type: 'context', num: 48, text: " <SettingsSection title=\"Appearance\">" },
            { type: 'add', num: 49, text: " <RadioGroup" },
            { type: 'add', num: 50, text: " value={colorScheme}" },
            { type: 'add', num: 51, text: " onChange={setColorScheme}" },
            { type: 'add', num: 52, text: " options={[" },
            { type: 'add', num: 53, text: " { value: 'system', label: 'System' }," },
            { type: 'add', num: 54, text: " { value: 'light', label: 'Light' }," },
            { type: 'add', num: 55, text: " { value: 'dark', label: 'Dark' }," },
            { type: 'add', num: 56, text: " ]}" },
            { type: 'add', num: 57, text: " />" },
            { type: 'context', num: 58, text: " </SettingsSection>" },
          ],
        },
      ],
    },
  },
  {
    id: 'n10',
    kind: 'tool',
    toolKind: 'bash',
    title: 'bash',
    subtitle: 'npm test -- settings',
    preview: '2 failed hydration mismatch on initial render',
    bashCommand: 'npm test -- settings',
    bashOutput:
      ' FAIL src/pages/settings.test.tsx\n renders accent options (24 ms)\n persists colorScheme to localStorage (31 ms)\n matches SSR render on mount (42 ms)\n\n matches SSR render on mount\n\n Warning: Text content did not match. Server: "light" Client: "dark"\n at SettingsPage (src/pages/SettingsPage.tsx:51:12)',
    timestamp: '01:54',
    duration: '6.2s',
    status: 'error',
  },
  {
    id: 'n11',
    kind: 'decision',
    title: 'hydration strategy',
    subtitle: '2 approaches considered',
    preview: 'chose: render "system" on SSR, sync on mount',
    timestamp: '02:05',
    duration: '0.9s',
    tokens: 824,
    status: 'complete',
    branch: {
      chosenLabel: 'render "system" on SSR sync scheme on mount',
      abandonedLabel: 'read scheme from httpOnly cookie server-side',
      abandonedReason:
        'requires middleware + cookie plumbing for a 14ms flash - not worth it',
    },
  },
  {
    id: 'n12',
    kind: 'tool',
    toolKind: 'edit',
    title: 'edit',
    subtitle: 'src/middleware.ts cookie-based scheme',
    preview: 'abandoned - would require SSR refactor',
    timestamp: '02:08',
    duration: '-',
    status: 'abandoned',
    isInBranch: 'abandoned',
  },
  {
    id: 'n13',
    kind: 'tool',
    toolKind: 'edit',
    title: 'edit',
    subtitle: 'src/theme/ThemeProvider.tsx',
    preview: '+11 -3 defer scheme resolution until after mount',
    timestamp: '02:19',
    duration: '0.5s',
    status: 'complete',
    isInBranch: 'chosen',
    diff: {
      file: 'src/theme/ThemeProvider.tsx',
      additions: 11,
      deletions: 3,
      hunks: [
        {
          header: '@@ -12,6 +12,14 @@',
          lines: [
            { type: 'context', num: 12, text: " const [mounted, setMounted] = useState(false);" },
            { type: 'remove', num: 13, text: " const [scheme, setScheme] = useState<ColorScheme>('system');" },
            { type: 'add', num: 13, text: " const [scheme, setScheme] = useState<ColorScheme>('system');" },
            { type: 'add', num: 14, text: "" },
            { type: 'add', num: 15, text: " useEffect(() => {" },
            { type: 'add', num: 16, text: " const stored = localStorage.getItem('theme.scheme') as ColorScheme | null;" },
            { type: 'add', num: 17, text: " if (stored) setScheme(stored);" },
            { type: 'add', num: 18, text: " setMounted(true);" },
            { type: 'add', num: 19, text: " }, []);" },
            { type: 'context', num: 20, text: "" },
            { type: 'context', num: 21, text: " const resolved = mounted ? scheme : 'system';" },
          ],
        },
      ],
    },
  },
  {
    id: 'n14',
    kind: 'tool',
    toolKind: 'bash',
    title: 'bash',
    subtitle: 'npm test -- settings',
    preview: '3 passed 0 failed',
    bashCommand: 'npm test -- settings',
    bashOutput:
      ' PASS src/pages/settings.test.tsx\n renders accent options (19 ms)\n persists colorScheme to localStorage (22 ms)\n matches SSR render on mount (28 ms)\n\nTest Suites: 1 passed, 1 total\nTests: 3 passed, 3 total\nTime: 4.118 s',
    timestamp: '02:38',
    duration: '4.1s',
    status: 'complete',
  },
  {
    id: 'n15',
    kind: 'milestone',
    title: 'feature complete',
    subtitle: 'dark mode toggle shipped tests green',
    preview: 'FOUC ~14ms cold load persists via localStorage',
    timestamp: '02:48',
    status: 'complete',
  },
];
