import type { ModelRef } from './swarm-types';

export const modelCatalog: ModelRef[] = [
  {
    id: 'opencode/claude-opus-4-7',
    label: 'claude-opus-4-7',
    provider: 'zen',
    family: 'claude',
    pricing: { input: 5, output: 25 },
  },
  {
    id: 'opencode/claude-sonnet-4-6',
    label: 'claude-sonnet-4-6',
    provider: 'zen',
    family: 'claude',
    pricing: { input: 3, output: 15 },
  },
  {
    id: 'opencode/claude-haiku-4-5',
    label: 'claude-haiku-4-5',
    provider: 'zen',
    family: 'claude',
    pricing: { input: 1, output: 5 },
  },
  {
    id: 'opencode/gpt-5.2',
    label: 'gpt-5.2',
    provider: 'zen',
    family: 'gpt',
    pricing: { input: 4, output: 20 },
  },
  {
    id: 'opencode/gemini-2.5-pro',
    label: 'gemini-2.5-pro',
    provider: 'zen',
    family: 'gemini',
    pricing: { input: 2.5, output: 12 },
  },
  {
    id: 'opencode/qwen3.6-plus',
    label: 'qwen3.6-plus',
    provider: 'go',
    family: 'qwen',
    pricing: { input: 0.5, output: 3 },
    limitTag: 'go 5h $12',
  },
  {
    id: 'opencode/kimi-k2',
    label: 'kimi-k2',
    provider: 'go',
    family: 'kimi',
    pricing: { input: 0.4, output: 2.5 },
    limitTag: 'go 5h $12',
  },
  {
    id: 'opencode/glm-4.6',
    label: 'glm-4.6',
    provider: 'go',
    family: 'glm',
    pricing: { input: 0.35, output: 2 },
    limitTag: 'go 5h $12',
  },
  {
    id: 'opencode/minimax-m2',
    label: 'minimax-m2',
    provider: 'go',
    family: 'minimax',
    pricing: { input: 0.3, output: 1.8 },
    limitTag: 'go 5h $12',
  },
  {
    id: 'byok/claude-opus-4-7',
    label: 'claude-opus-4-7',
    provider: 'byok',
    family: 'claude',
    pricing: { input: 5, output: 25 },
  },
];
